#!env bash
# push to Github
echo "****************************"
echo "Backing up $(pwd) to git"
echo "****************************"

echo "----------------------------"
echo "Installing git hound"
go get github.com/ezekg/git-hound
echo "----------------------------"
# install git secrets
cd $(pwd)


if [ ! -e .githound.yml ]
then
	curl https://gist.githubusercontent.com/souvikhaldar/e40f83b026ea04522a7993dda5785ed3/raw/cc6b2973b265086a83ce14f284da129bb6e7fbbd/gistfile1.txt -o .githound.yml
fi
# needs https://github.com/UKHomeOffice/repo-security-scanner
#echo "*******************************************"
#echo "Scanning filetypes and extensions"
#git log -p | scanrepo
#echo "*******************************************"

#echo "****************************"
#echo "git hound sniffing $(pwd)"
#echo "*******************************************"

#echo "*******************************************"
#echo "**********sniff entire codebase**************"
#git hound sniff
#echo "*******************************************"

#echo "*******************************************"
echo "**********sniff last commit change**************"
git hound sniff HEAD
#echo "*******************************************"



git add .
if [ -z "$1" ]
then
	git commit -m "New backup `date +'%Y-%m-%d %H:%M:%S'` ";
else
	git commit -m "$1";

fi

git push

